### ISSUE TITLE
Special 8chan-specific markup

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#88] opened 2019-04-20 17:10 UTC
1. Left-pointing arrow turning quotes pink (`< I am so so so stupid`) (a feature in 8chan)
2. Emphasis text that makes the text bold and red (a feature in 8chan)
3. A spoilered or blacked-out text for anime, comics or others
4. LaTeX-like formatting with `$$`
5. Bold, Italic, Strikethrough, Underline, Code, etc.

**Comment by DangerOnTheRanger** [comment] 2019-07-15 01:17
Duplicate of #116, so I'm closing this issue.

**Closed by DangerOnTheRanger** 2019-07-15 01:17 UTC
Labels: duplicate
