### ISSUE TITLE
META: General Feedback

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#84] opened 2019-04-20 16:51 UTC
According to an anonymous forum
>board urls don't use the board uri, so users can't access boards directly unless they memorize the numbers
>threads are globally numbered and don't contain the board uri, so users can't tell which boarda thread is from their url
>absolutely no caching
>nearly a whole second to respond with a page

**Comment by DangerOnTheRanger** [comment] 2019-04-20 22:44
>board urls don't use the board uri, so users can't access boards directly unless they memorize the numbers

This is something I want to implement (but haven't yet), but it's being tracked at #63.

>threads are globally numbered and don't contain the board uri, so users can't tell which boarda thread is from their url

This is a bit trickier. There's no need (from a technical perspective) to know which board a thread is located on if thread IDs are globally unique. So there's no technical reason to have board names in thread URLS as things are right now. I think there's a good case for readability's sake to include the board name in the URL, and for that reason I want to get around to it eventually. For me personally though, it's more of a slight cosmetic adjustment, so it's admittedly a lower priority.

>absolutely no caching

Very true, I hadn't gotten around to implementing caching yet. A key-value store is needed to run Maniwani as of a while ago, so caching should get done relatively soon.

>nearly a whole second to respond with a page

I haven't seen this personally myself outside of some REST API-related connection issues back in March with Futatsu, so I can't comment on this further. Page generation can be pretty slow on Futatsu admittedly (about 300-400ms), and I think that's worth looking into, but I also think proper caching should get around that problem until there's a Maniwani deployment with 4chan/8chan-level activity.

**Comment by samip5** [comment] 2019-12-09 03:05
@DangerOnTheRanger I'm thinking of deploying a such deployment, but what would be needed to be done for the caching? I know my way around Flask and Python.

**Comment by DangerOnTheRanger** [comment] 2019-12-09 12:10
Caching is much better at present than when this issue first came up; catalogs and threads both have ETag/304 Not Modified support now, so all that's left for full caching support is #105, so the reverse proxy itself can cache responses instead of each client caching pages.

**Comment by DangerOnTheRanger** [comment] 2020-10-05 07:16
Closing this as a now-duplicate of #105 and #63.

**Closed by DangerOnTheRanger** 2020-10-05 07:16 UTC
